# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/cons_new/eth_tx_gp_rx/eth_tx_gp_rx_top_pin_cons.xdc

# XDC: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/cons_new/eth_tx_gp_rx/eth_tx_gp_rx_top_time_cons.xdc

# XDC: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/cons_new/eth_tx_gp_rx/eth_tx_gp_rx_top_auto.xdc

# IP: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/tri_mode_ethernet_mac_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_mode_ethernet_mac_1 || ORIG_REF_NAME==tri_mode_ethernet_mac_1} -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/axis_dwidth_converter_1/axis_dwidth_converter_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dwidth_converter_1 || ORIG_REF_NAME==axis_dwidth_converter_1} -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_tx_gtp_rx_fifo/eth_tx_gtp_rx_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_tx_gtp_rx_fifo || ORIG_REF_NAME==eth_tx_gtp_rx_fifo} -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aurora_8b10b_rx || ORIG_REF_NAME==aurora_8b10b_rx} -quiet] -quiet

# IP: C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/global_clock_generation/global_clock_generation.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==global_clock_generation || ORIG_REF_NAME==global_clock_generation} -quiet] -quiet
