# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/tri_mode_ethernet_mac_1.xci
# IP: The module: 'tri_mode_ethernet_mac_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/tri_mode_ethernet_mac_1.xci
# IP: The module: 'tri_mode_ethernet_mac_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/tri_mode_ethernet_mac_1/synth/tri_mode_ethernet_mac_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tri_mode_ethernet_mac_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
