# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx.xci
# IP: The module: 'aurora_8b10b_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_8b10b_rx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_8b10b_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_8b10b_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx.xci
# IP: The module: 'aurora_8b10b_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_8b10b_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_8b10b_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/aurora_8b10b_rx/aurora_8b10b_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_8b10b_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
