# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.cache/wt} [current_project]
set_property parent.project_path {C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo {c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/imports/eth_rx_gtp_tx/clock_gen.v}
  {C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/imports/eth_rx_gtp_tx/reset_gen.v}
  {C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/imports/eth_rx_gtp_tx/s_axi_lite_control_generate.v}
  {C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/imports/eth_rx_gtp_tx/syn_block.v}
  {C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/imports/eth_rx_gtp_tx/eth_rx_gp_tx_top.v}
}
read_ip -quiet {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/aurora_8b10b_tx/aurora_8b10b_tx.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/aurora_8b10b_tx/aurora_8b10b_tx_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/aurora_8b10b_tx/aurora_8b10b_tx.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/aurora_8b10b_tx/aurora_8b10b_tx_ooc.xdc}}]

read_ip -quiet {{C:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/axis_dwidth_converter_0/axis_dwidth_converter_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/axis_dwidth_converter_0/axis_dwidth_converter_0_ooc.xdc}}]

read_ip -quiet {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo_ooc.xdc}}]

read_ip -quiet {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc}}]

read_ip -quiet {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/global_clock_generation/global_clock_generation.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/global_clock_generation/global_clock_generation_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/global_clock_generation/global_clock_generation.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/sources_1/ip/global_clock_generation/global_clock_generation_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/constrs_1/imports/eth_rx_gp_tx/eth_rx_gp_tx_top_cons_auto.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/constrs_1/imports/eth_rx_gp_tx/eth_rx_gp_tx_top_cons_auto.xdc}}]

read_xdc {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/constrs_1/imports/eth_rx_gp_tx/eth_rx_gp_tx_top_pin_cons.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/constrs_1/imports/eth_rx_gp_tx/eth_rx_gp_tx_top_pin_cons.xdc}}]

read_xdc {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/constrs_1/imports/eth_rx_gp_tx/eth_rx_gp_tx_top_time_cons.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/KANG Jian/Desktop/video_trans_advanced/eth_rx_gtp_tx/eth_rx_gtp_tx.srcs/constrs_1/imports/eth_rx_gp_tx/eth_rx_gp_tx_top_time_cons.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top eth_rx_gp_tx_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef eth_rx_gp_tx_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file eth_rx_gp_tx_top_utilization_synth.rpt -pb eth_rx_gp_tx_top_utilization_synth.pb"
