# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo.xci
# IP: The module: 'eth_rx_gtp_tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_rx_gtp_tx_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_rx_gtp_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_rx_gtp_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo.xci
# IP: The module: 'eth_rx_gtp_tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_rx_gtp_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_rx_gtp_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/eth_rx_gtp_tx_fifo/eth_rx_gtp_tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_rx_gtp_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
