# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/axis_dwidth_converter_1/axis_dwidth_converter_1.xci
# IP: The module: 'axis_dwidth_converter_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/axis_dwidth_converter_1/axis_dwidth_converter_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/axis_dwidth_converter_1/axis_dwidth_converter_1.xci
# IP: The module: 'axis_dwidth_converter_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/video_trans_advanced/video_trans_sourcecode/ip_new/axis_dwidth_converter_1/axis_dwidth_converter_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
